import React, { useCallback, useEffect, useState } from "react";
import { api } from "../services/api";
import { useAdmin } from "../context/AdminContext";
import { Empty, ErrorPanel, Loading, Modal, PageHeader } from "../components/Ui";

const blank = { name: "", contactName: "", phone: "", email: "", address: "", status: "active" };
export default function SuppliersPage() {
  const { notify } = useAdmin();
  const [items, setItems] = useState([]); const [form, setForm] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setItems((await api.get("/admin/suppliers")).data); } catch (e) { setError(e.message); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const save = async (event) => {
    event.preventDefault();
    try { const result = form.id ? await api.put(`/admin/suppliers/${form.id}`, form) : await api.post("/admin/suppliers", form); notify(result.message); setForm(null); load(); } catch (e) { notify(e.message, "error"); }
  };
  return <div><PageHeader eyebrow="Supply chain" title="Nhà cung cấp" copy="Quản lý đầu mối, thông tin liên hệ và trạng thái hợp tác." actions={<button className="ops-primary-button" onClick={() => setForm({ ...blank })} type="button">＋ Thêm nhà cung cấp</button>} />
    <section className="ops-mini-stats"><div><span>Tổng đối tác</span><strong>{items.length}</strong></div><div><span>Đang hợp tác</span><strong>{items.filter((item) => item.status === "active").length}</strong></div><div><span>Tạm dừng</span><strong>{items.filter((item) => item.status !== "active").length}</strong></div><div><span>Có thông tin liên hệ</span><strong>{items.filter((item) => item.phone || item.email).length}</strong></div></section>
    <section className="ops-panel ops-list-panel">{loading && <Loading rows={6} />}{error && <ErrorPanel message={error} onRetry={load} />}{!loading && !error && items.length > 0 && <div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Nhà cung cấp</th><th>Người liên hệ</th><th>Điện thoại</th><th>Email</th><th>Trạng thái</th><th /></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.address}</small></td><td>{item.contactName || "—"}</td><td>{item.phone || "—"}</td><td>{item.email || "—"}</td><td><span className={`ops-status ops-status--${item.status === "active" ? "green" : "neutral"}`}>{item.status === "active" ? "Đang hợp tác" : "Tạm dừng"}</span></td><td><div className="ops-row-actions"><button onClick={() => setForm({ ...item })} type="button">Sửa</button></div></td></tr>)}</tbody></table></div>}{!loading && !error && !items.length && <Empty title="Chưa có nhà cung cấp" copy="Thêm đối tác đầu tiên trước khi tạo phiếu nhập hàng." />}</section>
    <Modal open={Boolean(form)} title={form?.id ? "Chỉnh sửa nhà cung cấp" : "Thêm nhà cung cấp"} onClose={() => setForm(null)}>{form && <form className="ops-simple-form" onSubmit={save}><label className="ops-field"><span>Tên nhà cung cấp</span><input required minLength={2} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><div className="ops-form-grid"><label className="ops-field"><span>Người liên hệ</span><input value={form.contactName} onChange={(e) => setForm({ ...form, contactName: e.target.value })} /></label><label className="ops-field"><span>Điện thoại</span><input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></label><label className="ops-field"><span>Email</span><input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label className="ops-field"><span>Trạng thái</span><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option value="active">Đang hợp tác</option><option value="inactive">Tạm dừng</option></select></label><label className="ops-field ops-field--wide"><span>Địa chỉ</span><textarea rows={3} value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} /></label></div><div className="ops-form-actions"><button className="ops-secondary-button" onClick={() => setForm(null)} type="button">Hủy</button><button className="ops-primary-button" type="submit">Lưu nhà cung cấp</button></div></form>}</Modal>
  </div>;
}
